In [43]:
import numpy as np

prices = [55000, 55000, 70000, 52000, 32003, 55000, 120000, 30003]

arr = np.array(prices)

print(arr)

# condition applied to entire array → creates boolean mask
print(arr > 60000)

# arr[mask] → filters array and returns only masked elments which are true or satisfy the condition
print(arr[ (arr > 40000) & (arr <80000) ])


[ 55000  55000  70000  52000  32003  55000 120000  30003]
[False False  True False False False  True False]
[55000 55000 70000 52000 55000]


In [26]:
#How many orders are above 60000?
print(np.size(arr[arr > 60000]))

2


In [47]:
#Any price below 40000 should be treated as 40000 (minimum selling price policy)
arr[arr<40000] = 40000
print(arr)

[ 55000  55000  70000  52000  40000  55000 120000  40000]


In [52]:
# Create labels for each price in arr:
# if price ≥ 60000 → "Premium"
# otherwise → "Normal"

labels = np.where(arr>=60000, "Premium", "Normal")
print(labels)

[ 55000  55000  70000  52000  40000  55000 120000  40000]
['Normal' 'Normal' 'Premium' 'Normal' 'Normal' 'Normal' 'Premium' 'Normal']


In [53]:
#2d NumPy array
data = np.array([
    [55000, 2],
    [70000, 5],
    [30000, 1]
])

print(data)


[[55000     2]
 [70000     5]
 [30000     1]]


In [59]:
#2d numpy array operations 
print(data.shape)
print(data.sum())
print(data.sum(axis=0))
print(data.sum(axis=1))

(3, 2)
155008
[155000      8]
[55002 70005 30001]
